2018-10-31 17:23:16,335 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:23:17,396 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:23:18,506 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:23:19,665 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:23:20,874 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:23:22,137 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:23:23,449 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:23:24,810 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:23:26,222 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:23:27,686 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:23:29,202 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:23:30,766 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:23:32,378 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:23:34,038 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:23:35,754 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:23:39,632 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:23:41,447 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:23:43,307 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:23:45,222 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:23:47,185 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:23:49,198 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:23:51,260 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:23:53,372 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:23:55,531 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:23:57,746 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:24:00,007 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:24:02,317 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:24:04,677 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:24:07,084 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:24:09,544 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:24:12,058 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:24:14,620 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:24:17,231 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:24:19,894 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:24:22,605 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:24:25,365 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:24:28,176 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:24:31,037 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:24:33,946 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:24:36,906 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:24:39,915 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:24:42,930 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:24:45,939 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:24:48,948 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:24:51,958 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:24:54,969 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:24:57,981 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:25:00,992 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:25:04,000 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:25:07,008 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:25:10,021 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:25:13,032 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:25:16,044 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:25:19,055 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:25:22,064 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:25:25,075 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:25:28,087 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:25:31,095 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:25:34,104 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:25:37,113 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:25:40,121 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:25:43,131 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:25:46,141 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:25:49,151 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:25:52,160 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:25:55,174 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:25:58,185 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:26:01,196 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:26:04,205 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:26:07,215 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:26:10,225 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:26:13,234 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:26:16,240 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:26:19,251 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:26:22,259 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:26:25,273 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:26:28,282 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:26:31,289 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:26:34,298 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:26:37,307 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:26:40,319 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:26:43,329 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:26:46,339 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:26:49,349 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:26:52,360 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:26:55,367 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:26:58,381 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:27:01,390 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:27:04,397 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:27:07,407 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:27:10,416 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:27:13,427 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:27:16,434 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:27:19,446 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:27:22,458 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:27:25,471 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:27:28,481 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:27:31,493 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:27:34,504 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:27:37,513 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:27:40,521 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:27:43,530 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:27:46,541 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:27:49,548 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:27:52,557 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:27:55,563 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:27:58,572 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:28:01,582 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:28:04,592 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:28:07,604 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:28:10,613 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:28:13,623 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:28:16,635 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:28:19,644 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:28:22,653 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:28:25,665 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:28:28,675 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:28:31,686 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:28:34,697 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:28:37,707 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:28:40,725 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:28:43,734 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:28:46,743 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:28:49,752 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:28:52,764 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:28:55,773 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:28:58,783 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:29:01,791 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:29:04,800 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:29:07,809 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:29:10,819 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:29:13,830 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:29:16,840 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:29:19,850 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:29:22,859 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:29:25,871 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:29:28,882 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:29:31,892 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:29:34,901 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:29:37,911 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:29:40,921 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:29:43,928 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:29:46,939 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:29:49,949 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:29:52,958 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:29:55,967 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:29:58,977 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:30:01,986 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:30:04,998 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:30:08,010 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:30:11,020 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:30:14,033 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:30:17,047 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:30:20,057 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:30:23,066 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:30:26,075 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:30:29,086 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:30:32,095 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:30:35,105 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:30:38,115 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:30:41,130 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:30:44,137 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:30:47,149 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:30:50,161 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:30:53,171 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:30:56,182 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:30:59,193 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:31:02,203 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:31:05,214 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:31:08,225 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:31:11,235 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:31:14,244 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:31:17,254 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:31:20,263 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:31:23,275 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:31:26,286 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:31:29,296 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:31:32,305 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:31:35,315 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:31:38,322 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:31:41,332 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:31:44,351 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:31:47,361 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:31:50,372 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:31:53,384 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:31:56,394 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:31:59,406 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:32:02,417 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:32:05,428 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:32:08,440 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:32:11,451 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:32:14,463 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:32:17,473 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:32:20,485 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:32:23,497 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:32:26,508 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:32:29,518 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:32:32,526 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:32:35,533 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:32:38,545 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:32:41,557 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:32:44,567 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:32:47,580 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:32:50,589 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:32:53,599 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:32:56,607 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:32:59,619 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:33:02,633 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:33:05,643 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:33:08,657 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:33:11,668 ERROR 29888 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29888
hostname: LYU129PRI2

2018-10-31 17:53:35,949 ERROR 29152 [-/::1/-/169ms GET /findLists?pageNum=1&pageSize=10&search=] nodejs.ReplyError: ERR syntax error
    at JavascriptRedisParser.returnError (C:\Users\linge l yu\Desktop\egg-example\node_modules\ioredis\lib\redis\parser.js:24:25)
    at JavascriptRedisParser.execute (C:\Users\linge l yu\Desktop\egg-example\node_modules\redis-parser\lib\parser.js:572:12)
    at Socket.<anonymous> (C:\Users\linge l yu\Desktop\egg-example\node_modules\ioredis\lib\redis\event_handler.js:107:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
From previous event:
    at Command.initPromise (C:\Users\linge l yu\Desktop\egg-example\node_modules\ioredis\lib\command.js:63:18)
    at new Command (C:\Users\linge l yu\Desktop\egg-example\node_modules\ioredis\lib\command.js:51:8)
    at Redis.set (C:\Users\linge l yu\Desktop\egg-example\node_modules\ioredis\lib\commander.js:131:29)
    at ProductService.findLists (C:\Users\linge l yu\Desktop\egg-example\app\controller\product.js:11:25)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
name: "ReplyError"
message: "ERR syntax error"
command: {"name":"set","args":["lists","[object Object]","[object Object]","[object Object]"]}
headers: {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Credentials":"true"}
pid: 29152
hostname: LYU129PRI2

2018-10-31 17:54:30,810 ERROR 29152 [-/::1/-/111ms GET /findLists?pageNum=1&pageSize=10&search=] nodejs.ReplyError: ERR syntax error
    at JavascriptRedisParser.returnError (C:\Users\linge l yu\Desktop\egg-example\node_modules\ioredis\lib\redis\parser.js:24:25)
    at JavascriptRedisParser.execute (C:\Users\linge l yu\Desktop\egg-example\node_modules\redis-parser\lib\parser.js:572:12)
    at Socket.<anonymous> (C:\Users\linge l yu\Desktop\egg-example\node_modules\ioredis\lib\redis\event_handler.js:107:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
From previous event:
    at Command.initPromise (C:\Users\linge l yu\Desktop\egg-example\node_modules\ioredis\lib\command.js:63:18)
    at new Command (C:\Users\linge l yu\Desktop\egg-example\node_modules\ioredis\lib\command.js:51:8)
    at Redis.set (C:\Users\linge l yu\Desktop\egg-example\node_modules\ioredis\lib\commander.js:131:29)
    at ProductService.findLists (C:\Users\linge l yu\Desktop\egg-example\app\controller\product.js:11:25)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
name: "ReplyError"
message: "ERR syntax error"
command: {"name":"set","args":["lists","[object Object]","[object Object]","[object Object]"]}
headers: {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Credentials":"true"}
pid: 29152
hostname: LYU129PRI2

2018-10-31 19:23:51,158 ERROR 29152 nodejs.ECONNRESETError: read ECONNRESET
    at _errnoException (util.js:992:11)
    at TCP.onread (net.js:618:25)
code: "ECONNRESET"
errno: "ECONNRESET"
syscall: "read"
name: "ECONNRESETError"
pid: 29152
hostname: LYU129PRI2

2018-10-31 19:23:52,228 ERROR 29152 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29152
hostname: LYU129PRI2

2018-10-31 19:23:53,343 ERROR 29152 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29152
hostname: LYU129PRI2

2018-10-31 19:23:54,504 ERROR 29152 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29152
hostname: LYU129PRI2

2018-10-31 19:23:55,711 ERROR 29152 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29152
hostname: LYU129PRI2

2018-10-31 19:23:56,970 ERROR 29152 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 29152
hostname: LYU129PRI2

2018-11-02 11:21:55,805 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:21:56,868 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:21:57,978 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:21:59,138 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:22:00,347 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:22:01,608 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:22:02,917 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:22:04,275 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:22:05,685 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:22:04,978 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:22:06,038 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:22:07,146 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:22:07,157 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:22:08,657 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:22:08,317 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:22:09,525 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:22:10,215 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:22:10,783 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:22:11,830 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:22:12,094 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:22:13,490 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:22:13,450 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:22:14,859 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:22:15,202 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:22:16,319 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:22:16,964 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:22:17,830 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:22:18,773 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:22:19,391 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:22:20,632 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:22:21,001 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:22:22,540 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:22:22,659 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:22:24,500 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:22:24,369 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:22:26,507 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:22:26,128 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:22:27,938 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:22:28,569 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:22:29,801 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:22:30,676 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:22:31,709 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:22:32,837 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:22:33,670 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:22:35,045 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:22:35,681 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:22:37,304 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:22:37,740 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:22:39,611 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:22:39,847 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:22:41,969 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:22:42,004 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:22:44,377 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:22:44,213 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:22:46,471 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:22:46,834 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:22:48,779 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:22:49,343 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:22:51,137 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:22:51,903 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:22:53,544 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:22:54,511 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:22:56,002 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:22:57,168 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:22:58,509 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:22:59,877 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:23:01,067 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:23:02,635 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:23:03,677 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:23:05,443 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:23:06,335 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:23:08,302 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:23:09,043 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:23:11,213 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:23:11,805 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:23:14,171 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:23:14,615 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:23:17,181 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:23:17,473 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:23:20,191 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:23:20,382 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:23:23,199 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:23:23,339 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:23:26,208 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:23:26,349 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:23:29,217 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:23:29,357 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:23:32,225 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:23:32,365 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:23:35,235 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:23:35,374 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:23:38,245 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:23:38,381 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:23:41,254 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:23:41,389 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:23:44,261 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:23:44,397 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:23:47,266 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:23:47,406 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:23:50,277 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:23:50,413 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:23:53,285 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:23:53,421 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:23:56,294 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:23:56,428 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:23:59,302 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:23:59,436 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:24:02,310 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:24:02,444 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:24:05,319 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:24:05,451 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:24:08,326 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:24:08,459 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:24:11,335 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:24:11,469 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:24:14,345 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:24:14,476 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:24:17,355 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:24:17,484 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:24:20,366 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:24:20,492 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:24:23,375 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:24:23,500 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:24:26,384 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:24:26,507 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:24:29,395 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:24:29,516 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:24:32,402 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:24:32,525 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:24:35,411 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:24:35,531 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:24:38,419 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:24:38,539 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:24:41,427 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:24:41,549 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:24:44,439 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:24:44,561 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 11:24:47,448 ERROR 31172 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 31172
hostname: LYU129PRI2

2018-11-02 11:24:47,573 ERROR 2036 nodejs.ECONNREFUSEDError: connect ECONNREFUSED 127.0.0.1:6379
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
code: "ECONNREFUSED"
errno: "ECONNREFUSED"
syscall: "connect"
address: "127.0.0.1"
port: 6379
name: "ECONNREFUSEDError"
pid: 2036
hostname: LYU129PRI2

2018-11-02 13:59:48,606 ERROR 38804 nodejs.unhandledExceptionError: read ECONNRESET
    at _errnoException (util.js:992:11)
    at TCP.onread (net.js:618:25)
code: "ECONNRESET"
errno: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 38804
hostname: LYU129PRI2

2018-11-02 14:29:14,737 ERROR 37676 [-/::1/-/5ms POST /upload] nodejs.TypeError: Cannot read property 'file' of undefined
    at uploadFiles (C:\Users\linge l yu\Desktop\egg-example\app\controller\upload.js:12:39)
    at Object.callFn (C:\Users\linge l yu\Desktop\egg-example\node_modules\egg-core\lib\utils\index.js:36:21)
    at Object.classControllerMiddleware (C:\Users\linge l yu\Desktop\egg-example\node_modules\egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\Users\linge l yu\Desktop\egg-example\node_modules\egg-core\lib\utils\index.js:36:21)
    at wrappedController (C:\Users\linge l yu\Desktop\egg-example\node_modules\egg-core\lib\utils\router.js:322:18)
    at dispatch (C:\Users\linge l yu\Desktop\egg-example\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (C:\Users\linge l yu\Desktop\egg-example\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at C:\Users\linge l yu\Desktop\egg-example\node_modules\koa-router\lib\router.js:346:16
    at dispatch (C:\Users\linge l yu\Desktop\egg-example\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at C:\Users\linge l yu\Desktop\egg-example\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
    at dispatch (C:\Users\linge l yu\Desktop\egg-example\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (C:\Users\linge l yu\Desktop\egg-example\node_modules\koa-compose\index.js:42:32)
    at C:\Users\linge l yu\Desktop\egg-example\node_modules\egg-development\app\middleware\egg_loader_trace.js:9:56
    at dispatch (C:\Users\linge l yu\Desktop\egg-example\node_modules\koa-compose\index.js:42:32)
    at i18n (C:\Users\linge l yu\Desktop\egg-example\node_modules\egg-i18n\app\middleware\i18n.js:13:12)
    at dispatch (C:\Users\linge l yu\Desktop\egg-example\node_modules\koa-compose\index.js:42:32)
headers: {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Credentials":"true"}
pid: 37676
hostname: LYU129PRI2

2018-11-02 15:54:47,655 ERROR 27148 [-/::1/-/20ms POST /upload] nodejs.TypeError: the multipart request can't be consumed twice
    at Object.multipart (C:\Users\linge l yu\Desktop\egg-example\node_modules\egg-multipart\app\extend\context.js:26:35)
    at Object.getFileStream (C:\Users\linge l yu\Desktop\egg-example\node_modules\egg-multipart\app\extend\context.js:50:24)
    at uploadFiles (C:\Users\linge l yu\Desktop\egg-example\app\controller\upload.js:10:34)
    at Object.callFn (C:\Users\linge l yu\Desktop\egg-example\node_modules\egg-core\lib\utils\index.js:36:21)
    at Object.classControllerMiddleware (C:\Users\linge l yu\Desktop\egg-example\node_modules\egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\Users\linge l yu\Desktop\egg-example\node_modules\egg-core\lib\utils\index.js:36:21)
    at wrappedController (C:\Users\linge l yu\Desktop\egg-example\node_modules\egg-core\lib\utils\router.js:322:18)
    at dispatch (C:\Users\linge l yu\Desktop\egg-example\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at next (C:\Users\linge l yu\Desktop\egg-example\node_modules\koa-router\node_modules\koa-compose\index.js:45:18)
    at C:\Users\linge l yu\Desktop\egg-example\node_modules\koa-router\lib\router.js:346:16
    at dispatch (C:\Users\linge l yu\Desktop\egg-example\node_modules\koa-router\node_modules\koa-compose\index.js:44:32)
    at C:\Users\linge l yu\Desktop\egg-example\node_modules\koa-router\node_modules\koa-compose\index.js:36:12
    at dispatch (C:\Users\linge l yu\Desktop\egg-example\node_modules\koa-router\lib\router.js:351:31)
    at dispatch (C:\Users\linge l yu\Desktop\egg-example\node_modules\koa-compose\index.js:42:32)
    at C:\Users\linge l yu\Desktop\egg-example\node_modules\egg-development\app\middleware\egg_loader_trace.js:9:56
    at dispatch (C:\Users\linge l yu\Desktop\egg-example\node_modules\koa-compose\index.js:42:32)
headers: {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Credentials":"true"}
pid: 27148
hostname: LYU129PRI2

2018-11-02 16:01:36,309 ERROR 35832 nodejs.ServerNoResponseError: server 127.0.0.1:49793 no response in 20002ms, maybe the socket is end on the other side. (address: 127.0.0.1:49793)
    at Timeout._heartbeatTimer.setInterval [as _onTimeout] (C:\Users\linge l yu\Desktop\egg-example\node_modules\tcp-base\lib\base.js:427:21)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ServerNoResponseError"
pid: 35832
hostname: LYU129PRI2

2018-11-02 16:04:08,757 ERROR 10324 nodejs.ServerNoResponseError: server 127.0.0.1:51203 no response in 40002ms, maybe the socket is end on the other side. (address: 127.0.0.1:51203)
    at Timeout._heartbeatTimer.setInterval [as _onTimeout] (C:\Users\linge l yu\Desktop\egg-example\node_modules\tcp-base\lib\base.js:427:21)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ServerNoResponseError"
pid: 10324
hostname: LYU129PRI2

2018-11-02 16:04:22,687 ERROR 24752 nodejs.ClusterClientNoResponseError: client no response in 73925ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (C:\Users\linge l yu\Desktop\egg-example\node_modules\cluster-client\lib\leader.js:74:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 24752
hostname: LYU129PRI2

2018-11-02 16:05:45,088 ERROR 22108 nodejs.ENOENTError: ENOENT: no such file or directory, open 'C:\Users\linge l yu\Desktop\egg-example\app\public\file\1541145945083Confirmation centre -FAQ 1031 .xlsx' (uncaughtException throw 1 times on pid:22108)
ENOENTError: ENOENT: no such file or directory, open 'C:\Users\linge l yu\Desktop\egg-example\app\public\file\1541145945083Confirmation centre -FAQ 1031 .xlsx' (uncaughtException throw 1 times on pid:22108)
errno: -4058
code: "ENOENT"
syscall: "open"
path: "C:\\Users\\linge l yu\\Desktop\\egg-example\\app\\public\\file\\1541145945083Confirmation centre -FAQ 1031 .xlsx"
name: "ENOENTError"
pid: 22108
hostname: LYU129PRI2

2018-11-02 16:57:39,008 ERROR 16908 nodejs.unhandledExceptionError: read ECONNRESET
    at _errnoException (util.js:992:11)
    at TCP.onread (net.js:618:25)
code: "ECONNRESET"
errno: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 16908
hostname: LYU129PRI2

2018-11-05 17:00:34,189 ERROR 8512 [-/::1/-/14ms GET /findLists?pageNum=1&pageSize=10&search=] nodejs.ReplyError: ERR syntax error
    at JavascriptRedisParser.returnError (C:\Users\linge l yu\Desktop\egg-example\node_modules\ioredis\lib\redis\parser.js:24:25)
    at JavascriptRedisParser.execute (C:\Users\linge l yu\Desktop\egg-example\node_modules\redis-parser\lib\parser.js:572:12)
    at Socket.<anonymous> (C:\Users\linge l yu\Desktop\egg-example\node_modules\ioredis\lib\redis\event_handler.js:107:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
From previous event:
    at Command.initPromise (C:\Users\linge l yu\Desktop\egg-example\node_modules\ioredis\lib\command.js:63:18)
    at new Command (C:\Users\linge l yu\Desktop\egg-example\node_modules\ioredis\lib\command.js:51:8)
    at Redis.set (C:\Users\linge l yu\Desktop\egg-example\node_modules\ioredis\lib\commander.js:131:29)
    at ProductService.findLists (C:\Users\linge l yu\Desktop\egg-example\app\controller\product.js:11:25)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
name: "ReplyError"
message: "ERR syntax error"
command: {"name":"set","args":["lists","[object Object]","[object Object]","[object Object]"]}
headers: {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Credentials":"true"}
pid: 8512
hostname: LYU129PRI2

2018-11-05 17:00:40,825 ERROR 8512 [-/::1/-/5ms GET /findLists?pageNum=1&pageSize=10&search=] nodejs.ReplyError: ERR syntax error
    at JavascriptRedisParser.returnError (C:\Users\linge l yu\Desktop\egg-example\node_modules\ioredis\lib\redis\parser.js:24:25)
    at JavascriptRedisParser.execute (C:\Users\linge l yu\Desktop\egg-example\node_modules\redis-parser\lib\parser.js:572:12)
    at Socket.<anonymous> (C:\Users\linge l yu\Desktop\egg-example\node_modules\ioredis\lib\redis\event_handler.js:107:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
From previous event:
    at Command.initPromise (C:\Users\linge l yu\Desktop\egg-example\node_modules\ioredis\lib\command.js:63:18)
    at new Command (C:\Users\linge l yu\Desktop\egg-example\node_modules\ioredis\lib\command.js:51:8)
    at Redis.set (C:\Users\linge l yu\Desktop\egg-example\node_modules\ioredis\lib\commander.js:131:29)
    at ProductService.findLists (C:\Users\linge l yu\Desktop\egg-example\app\controller\product.js:11:25)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
name: "ReplyError"
message: "ERR syntax error"
command: {"name":"set","args":["lists","[object Object]","[object Object]","[object Object]"]}
headers: {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Credentials":"true"}
pid: 8512
hostname: LYU129PRI2

2018-11-05 17:02:42,536 ERROR 15024 [-/::1/-/16ms GET /findLists?pageNum=1&pageSize=10&search=] nodejs.ReplyError: ERR syntax error
    at JavascriptRedisParser.returnError (C:\Users\linge l yu\Desktop\egg-example\node_modules\ioredis\lib\redis\parser.js:24:25)
    at JavascriptRedisParser.execute (C:\Users\linge l yu\Desktop\egg-example\node_modules\redis-parser\lib\parser.js:572:12)
    at Socket.<anonymous> (C:\Users\linge l yu\Desktop\egg-example\node_modules\ioredis\lib\redis\event_handler.js:107:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
From previous event:
    at Command.initPromise (C:\Users\linge l yu\Desktop\egg-example\node_modules\ioredis\lib\command.js:63:18)
    at new Command (C:\Users\linge l yu\Desktop\egg-example\node_modules\ioredis\lib\command.js:51:8)
    at Redis.set (C:\Users\linge l yu\Desktop\egg-example\node_modules\ioredis\lib\commander.js:131:29)
    at ProductService.findLists (C:\Users\linge l yu\Desktop\egg-example\app\controller\product.js:11:25)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
name: "ReplyError"
message: "ERR syntax error"
command: {"name":"set","args":["lists","[object Object]","[object Object]","[object Object]"]}
headers: {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Credentials":"true"}
pid: 15024
hostname: LYU129PRI2

2018-11-05 17:03:26,626 ERROR 15300 [-/::1/-/16ms GET /findLists?pageNum=1&pageSize=10&search=] nodejs.ReplyError: ERR syntax error
    at JavascriptRedisParser.returnError (C:\Users\linge l yu\Desktop\egg-example\node_modules\ioredis\lib\redis\parser.js:24:25)
    at JavascriptRedisParser.execute (C:\Users\linge l yu\Desktop\egg-example\node_modules\redis-parser\lib\parser.js:572:12)
    at Socket.<anonymous> (C:\Users\linge l yu\Desktop\egg-example\node_modules\ioredis\lib\redis\event_handler.js:107:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
From previous event:
    at Command.initPromise (C:\Users\linge l yu\Desktop\egg-example\node_modules\ioredis\lib\command.js:63:18)
    at new Command (C:\Users\linge l yu\Desktop\egg-example\node_modules\ioredis\lib\command.js:51:8)
    at Redis.set (C:\Users\linge l yu\Desktop\egg-example\node_modules\ioredis\lib\commander.js:131:29)
    at ProductService.findLists (C:\Users\linge l yu\Desktop\egg-example\app\controller\product.js:11:25)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
name: "ReplyError"
message: "ERR syntax error"
command: {"name":"set","args":["lists","[object Object]","[object Object]","[object Object]"]}
headers: {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Credentials":"true"}
pid: 15300
hostname: LYU129PRI2

2018-11-05 17:06:20,317 ERROR 15156 [-/::1/-/8ms GET /findLists?pageNum=1&pageSize=10&search=] nodejs.ReplyError: ERR syntax error
    at JavascriptRedisParser.returnError (C:\Users\linge l yu\Desktop\egg-example\node_modules\ioredis\lib\redis\parser.js:24:25)
    at JavascriptRedisParser.execute (C:\Users\linge l yu\Desktop\egg-example\node_modules\redis-parser\lib\parser.js:572:12)
    at Socket.<anonymous> (C:\Users\linge l yu\Desktop\egg-example\node_modules\ioredis\lib\redis\event_handler.js:107:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
From previous event:
    at Command.initPromise (C:\Users\linge l yu\Desktop\egg-example\node_modules\ioredis\lib\command.js:63:18)
    at new Command (C:\Users\linge l yu\Desktop\egg-example\node_modules\ioredis\lib\command.js:51:8)
    at Redis.set (C:\Users\linge l yu\Desktop\egg-example\node_modules\ioredis\lib\commander.js:131:29)
    at ProductService.findLists (C:\Users\linge l yu\Desktop\egg-example\app\controller\product.js:11:25)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
name: "ReplyError"
message: "ERR syntax error"
command: {"name":"set","args":["lists","[object Object]","[object Object]","[object Object]"]}
headers: {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Credentials":"true"}
pid: 15156
hostname: LYU129PRI2

2018-11-05 17:14:35,270 ERROR 1240 nodejs.SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at C:\Users\linge l yu\Desktop\egg-example\app\controller\product.js:14:43
    at <anonymous>

pid: 1240
hostname: LYU129PRI2

2018-11-05 17:20:19,909 ERROR 13036 nodejs.ReplyError: ERR wrong number of arguments for 'hmget' command
    at JavascriptRedisParser.returnError (C:\Users\linge l yu\Desktop\egg-example\node_modules\ioredis\lib\redis\parser.js:24:25)
    at JavascriptRedisParser.execute (C:\Users\linge l yu\Desktop\egg-example\node_modules\redis-parser\lib\parser.js:572:12)
    at Socket.<anonymous> (C:\Users\linge l yu\Desktop\egg-example\node_modules\ioredis\lib\redis\event_handler.js:107:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
From previous event:
    at Command.initPromise (C:\Users\linge l yu\Desktop\egg-example\node_modules\ioredis\lib\command.js:63:18)
    at new Command (C:\Users\linge l yu\Desktop\egg-example\node_modules\ioredis\lib\command.js:51:8)
    at Redis.hmget (C:\Users\linge l yu\Desktop\egg-example\node_modules\ioredis\lib\commander.js:131:29)
    at C:\Users\linge l yu\Desktop\egg-example\app\controller\product.js:13:40
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
name: "ReplyError"
message: "ERR wrong number of arguments for 'hmget' command"
command: {"name":"hmget","args":["lists"]}
pid: 13036
hostname: LYU129PRI2

2018-11-05 17:22:52,844 ERROR 1640 nodejs.TypeError: app.redis.hmgetall is not a function
    at C:\Users\linge l yu\Desktop\egg-example\app\controller\product.js:13:40
    at tryCatcher (C:\Users\linge l yu\Desktop\egg-example\node_modules\bluebird\js\release\util.js:16:23)
    at Promise.successAdapter [as _fulfillmentHandler0] (C:\Users\linge l yu\Desktop\egg-example\node_modules\bluebird\js\release\nodeify.js:23:30)
    at Promise._settlePromise (C:\Users\linge l yu\Desktop\egg-example\node_modules\bluebird\js\release\promise.js:566:21)
    at Promise._settlePromise0 (C:\Users\linge l yu\Desktop\egg-example\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\linge l yu\Desktop\egg-example\node_modules\bluebird\js\release\promise.js:694:18)
    at _drainQueueStep (C:\Users\linge l yu\Desktop\egg-example\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (C:\Users\linge l yu\Desktop\egg-example\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (C:\Users\linge l yu\Desktop\egg-example\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (C:\Users\linge l yu\Desktop\egg-example\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)

pid: 1640
hostname: LYU129PRI2

2018-11-05 17:23:33,239 ERROR 244 nodejs.ReplyError: WRONGTYPE Operation against a key holding the wrong kind of value
    at JavascriptRedisParser.returnError (C:\Users\linge l yu\Desktop\egg-example\node_modules\ioredis\lib\redis\parser.js:24:25)
    at JavascriptRedisParser.execute (C:\Users\linge l yu\Desktop\egg-example\node_modules\redis-parser\lib\parser.js:572:12)
    at Socket.<anonymous> (C:\Users\linge l yu\Desktop\egg-example\node_modules\ioredis\lib\redis\event_handler.js:107:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
From previous event:
    at Command.initPromise (C:\Users\linge l yu\Desktop\egg-example\node_modules\ioredis\lib\command.js:63:18)
    at new Command (C:\Users\linge l yu\Desktop\egg-example\node_modules\ioredis\lib\command.js:51:8)
    at Redis.hgetall (C:\Users\linge l yu\Desktop\egg-example\node_modules\ioredis\lib\commander.js:131:29)
    at C:\Users\linge l yu\Desktop\egg-example\app\controller\product.js:13:40
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
name: "ReplyError"
message: "WRONGTYPE Operation against a key holding the wrong kind of value"
command: {"name":"hgetall","args":["lists"]}
pid: 244
hostname: LYU129PRI2

2018-11-05 17:24:28,007 ERROR 9412 nodejs.ReplyError: WRONGTYPE Operation against a key holding the wrong kind of value
    at JavascriptRedisParser.returnError (C:\Users\linge l yu\Desktop\egg-example\node_modules\ioredis\lib\redis\parser.js:24:25)
    at JavascriptRedisParser.execute (C:\Users\linge l yu\Desktop\egg-example\node_modules\redis-parser\lib\parser.js:572:12)
    at Socket.<anonymous> (C:\Users\linge l yu\Desktop\egg-example\node_modules\ioredis\lib\redis\event_handler.js:107:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:597:20)
From previous event:
    at Command.initPromise (C:\Users\linge l yu\Desktop\egg-example\node_modules\ioredis\lib\command.js:63:18)
    at new Command (C:\Users\linge l yu\Desktop\egg-example\node_modules\ioredis\lib\command.js:51:8)
    at Redis.hgetall (C:\Users\linge l yu\Desktop\egg-example\node_modules\ioredis\lib\commander.js:131:29)
    at C:\Users\linge l yu\Desktop\egg-example\app\controller\product.js:13:40
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
name: "ReplyError"
message: "WRONGTYPE Operation against a key holding the wrong kind of value"
command: {"name":"hgetall","args":["lists"]}
pid: 9412
hostname: LYU129PRI2

2018-11-05 18:02:44,407 ERROR 11716 nodejs.unhandledExceptionError: read ECONNRESET
    at _errnoException (util.js:992:11)
    at TCP.onread (net.js:618:25)
code: "ECONNRESET"
errno: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 11716
hostname: LYU129PRI2

2018-11-06 11:00:53,531 ERROR 11716 nodejs.ClusterClientNoResponseError: client no response in 57508606ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout.Leader._heartbeatTimer.setInterval [as _onTimeout] (C:\Users\linge l yu\Desktop\egg-example\node_modules\cluster-client\lib\leader.js:74:23)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
name: "ClusterClientNoResponseError"
pid: 11716
hostname: LYU129PRI2

